server:
  http_listen_address:  127.0.0.1
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # Loki server URL

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
      - loki
    labels:
      job: varlogs
      __path__: /var/log/*log
